"""initial schema

Revision ID: 6e0d44ba8d56
Revises: 
Create Date: 2026-09-18 01:04:52.563717
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '6e0d44ba8d56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('runs_started', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('client_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demo_sessions'))
    )
    op.create_table('guide_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_session_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('city_hint', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('active_owner_key', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_session_id'], ['demo_sessions.id'], name=op.f('fk_guide_projects_owner_session_id_demo_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guide_projects')),
    sa.UniqueConstraint('active_owner_key', name='uq_projects_active_owner')
    )
    op.create_index('ix_projects_owner_status', 'guide_projects', ['owner_session_id', 'status'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['demo_sessions.id'], name=op.f('fk_usage_ledger_session_id_demo_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_ledger'))
    )
    op.create_index('ix_usage_day', 'usage_ledger', ['day'], unique=False)
    op.create_index('ix_usage_session_day', 'usage_ledger', ['session_id', 'day'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['guide_projects.id'], name=op.f('fk_media_assets_project_id_guide_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('project_id', 'position', name='uq_media_project_position')
    )
    op.create_index('ix_media_project_created', 'media_assets', ['project_id', 'created_at'], unique=False)
    op.create_table('workspace_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('media_asset_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['guide_projects.id'], name=op.f('fk_workspace_events_project_id_guide_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_events'))
    )
    op.create_index('ix_events_project_id', 'workspace_events', ['project_id', 'id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('media_asset_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_step', sa.String(length=48), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('budget_max_steps', sa.Integer(), nullable=False),
    sa.Column('budget_max_tool_calls', sa.Integer(), nullable=False),
    sa.Column('budget_max_tokens', sa.Integer(), nullable=False),
    sa.Column('budget_max_cost_usd', sa.Float(), nullable=False),
    sa.Column('used_steps', sa.Integer(), nullable=False),
    sa.Column('used_tool_calls', sa.Integer(), nullable=False),
    sa.Column('used_tokens', sa.Integer(), nullable=False),
    sa.Column('used_cost_usd', sa.Float(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_agent_runs_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['guide_projects.id'], name=op.f('fk_agent_runs_project_id_guide_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_runs_project_idempotency')
    )
    op.create_index('ix_runs_media_created', 'agent_runs', ['media_asset_id', 'created_at'], unique=False)
    op.create_index('ix_runs_status_lease', 'agent_runs', ['status', 'lease_expires_at'], unique=False)
    op.create_table('place_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_asset_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_place_candidates_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_place_candidates_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_candidates')),
    sa.UniqueConstraint('run_id', 'rank', name='uq_candidates_run_rank')
    )
    op.create_index('ix_candidates_media_status', 'place_candidates', ['media_asset_id', 'status'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('media_asset_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_place_id', sa.String(length=128), nullable=True),
    sa.Column('provider_payload', sa.JSON(), nullable=True),
    sa.Column('query_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_places_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['guide_projects.id'], name=op.f('fk_places_project_id_guide_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_places_run_id_agent_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places')),
    sa.UniqueConstraint('media_asset_id', name='uq_places_media_asset')
    )
    op.create_table('run_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_run_steps_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_steps')),
    sa.UniqueConstraint('run_id', 'name', name='uq_run_steps_run_name')
    )
    op.create_table('guide_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('media_asset_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('tips', sa.JSON(), nullable=True),
    sa.Column('place_facts', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('partial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_guide_cards_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_guide_cards_place_id_places'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['guide_projects.id'], name=op.f('fk_guide_cards_project_id_guide_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_guide_cards_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guide_cards')),
    sa.UniqueConstraint('media_asset_id', name='uq_cards_media_asset')
    )
    op.create_index('ix_cards_project', 'guide_cards', ['project_id', 'created_at'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('request_summary', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_prompt', sa.Integer(), nullable=False),
    sa.Column('tokens_completion', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_tool_invocations_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['run_steps.id'], name=op.f('fk_tool_invocations_step_id_run_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_invocations'))
    )
    op.create_index('ix_tool_invocations_run', 'tool_invocations', ['run_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL 不允许 DROP INDEX 掉外键依赖的索引（errno 1553），
    # 因此回退时只删表：DROP TABLE 会连带删除索引和外键。
    # 回退顺序为依赖关系的逆序。
    op.drop_table('tool_invocations')
    op.drop_table('guide_cards')
    op.drop_table('run_steps')
    op.drop_table('places')
    op.drop_table('place_candidates')
    op.drop_table('agent_runs')
    op.drop_table('workspace_events')
    op.drop_table('media_assets')
    op.drop_table('usage_ledger')
    op.drop_table('guide_projects')
    op.drop_table('demo_sessions')
